# Customize table headers
column_names:
    ID: ID
    t: t
    var_name: variable_name
    var_value: variable_value

parallel: yes
n_jobs: 72
batch_size: 100

hierarchical_sep: ":"
hierarchical_levels: [0, 1, 2]

discretize: yes
use_ordinal_encoding: no
discretization: ~

value_types:
    # enter the feature type that you would like to override in the following format:
    FIRST_WARDID: Categorical
    MedA_AMOUNT: Numeric
    MedA_ROUTE: Categorical
    ICD9_CODE: hierarchical_ICD9
